# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'iot-lis-client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iot-lis-client

  target 'iot-lis-clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iot-lis-clientUITests' do
    # Pods for testing
  end

end
