pool:
    vmImage: 'ubuntu-latest'

variables:
  scheme: 'LISManager'
  sdk: 'iphoneos'
  configuration: 'Release'

stages:
    - stage: Build
      displayName: Build Source Code
      jobs:
        - job: Compile_Go
          displayName: Compile Go Projects
          steps:
            - checkout: self
              submodules: true
            - task: GoTool@0
              displayName: Install Go Tools
              inputs:
                version: '1.15.3'
            - task: Go@0
              displayName: Go get
              inputs:
                command: 'get'
                arguments: '-d'
                workingDirectory: '$(System.DefaultWorkingDirectory)/server'
            - task: Go@0
              displayName: Go build
              inputs:
                command: 'build'
                workingDirectory: '$(System.DefaultWorkingDirectory)/server'
            - task: Go@0
              displayName: Go test
              inputs:
                command: 'test'
                arguments: '-v -race'
                workingDirectory: '$(System.DefaultWorkingDirectory)/server'
        - job: Compile_iOS
          displayName: Compile iOS Projects
          pool:
            vmImage: 'macOS-10.15'
          steps:
          - checkout: self
            submodules: true
            lfs: true
          - bash: |
              brew install flatbuffers --HEAD
            displayName: Install system dependencies
          - task: CocoaPods@0
            inputs:
              workingDirectory: 'ios/LISManager'
              forceRepoUpdate: false
          - task: Xcode@5
            inputs:
              sdk: '$(sdk)'
              scheme: '$(scheme)'
              configuration: '$(configuration)'
              xcodeVersion: '11' # Options: default, 10, 9, 8, specifyPath
              exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
              xcWorkspacePath: ios/LISManager/LISManager.xcworkspace
