pool:
    vmImage: 'ubuntu-latest'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

stages:
    - stage: Build
      displayName: Build Source Code
      jobs:
        - job: Compile_Go
          displayName: Compile Go Projects
          steps:
            - checkout: self
              submodules: true
            - task: GoTool@0
              inputs:
                version: '1.15.3'
            - task: Go@0
              inputs:
                command: 'get'
                arguments: '-d'
                workingDirectory: '$(System.DefaultWorkingDirectory)/server'
            - task: Go@0
              inputs:
                command: 'build'
                workingDirectory: '$(System.DefaultWorkingDirectory)/server'
            - task: Go@0
              inputs:
                command: 'test'
                arguments: '-v'
                workingDirectory: '$(modulePath)'
        - job: Compile_iOS
          displayName: Compile iOS Projects
          steps:
          - task: Xcode@5
            inputs:
              sdk: '$(sdk)'
              scheme: '$(scheme)'
              configuration: '$(configuration)'
              xcodeVersion: '11' # Options: default, 10, 9, 8, specifyPath
              exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
              xcWorkspacePath: ios/LISManager/LISManager.xcworkspace
