// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocols

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Comment struct {
	_tab flatbuffers.Table
}

func GetRootAsComment(buf []byte, offset flatbuffers.UOffsetT) *Comment {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Comment{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Comment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Comment) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Comment) SequenceNumber() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Comment) MutateSequenceNumber(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Comment) TestMode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CommentStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CommentAddSequenceNumber(builder *flatbuffers.Builder, sequenceNumber int32) {
	builder.PrependInt32Slot(0, sequenceNumber, 0)
}
func CommentAddTestMode(builder *flatbuffers.Builder, testMode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(testMode), 0)
}
func CommentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
