// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocols

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EchoSend struct {
	_tab flatbuffers.Table
}

func GetRootAsEchoSend(buf []byte, offset flatbuffers.UOffsetT) *EchoSend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EchoSend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EchoSend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EchoSend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EchoSend) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EchoSendStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EchoSendAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func EchoSendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
