disabled_rules:
  - trailing_whitespace

excluded:
  - Pods
  - "*/API.swift"

line_length: 200

identifier_name:
  min_length: # only min_length
    warning: 2 # only error
  max_length:
    warning: 30
