# Uncomment the next line to define a global platform for your project
platform :ios, '13.3'

target 'LISManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'xxHash-Swift'
  pod 'SwiftLint'
  pod 'OktaOidc'
  pod 'OktaStorage'
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'

  # Pods for LISManager

  target 'LISManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LISManagerUITests' do
    # Pods for testing
  end

end

target 'LISKit' do
  use_frameworks!

  pod 'FlatBuffers', :git => 'https://github.com/mustiikhalil/flatbuffers.git'

  target 'LISKitTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
